/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ImariCredentialRegistry {
  export type RecordStruct = {
    contentHash: BytesLike;
    issuedAt: BigNumberish;
    revokedAt: BigNumberish;
    status: BigNumberish;
  };

  export type RecordStructOutput = [
    contentHash: string,
    issuedAt: bigint,
    revokedAt: bigint,
    status: bigint
  ] & {
    contentHash: string;
    issuedAt: bigint;
    revokedAt: bigint;
    status: bigint;
  };
}

export interface ImariCredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "get"
      | "issue"
      | "issuers"
      | "owner"
      | "paused"
      | "reinstate"
      | "revoke"
      | "setIssuer"
      | "setPaused"
      | "transferOwnership"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialReinstated"
      | "CredentialRevoked"
      | "IssuerSet"
      | "Paused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "get", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "issue",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reinstate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "revoke", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setIssuer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reinstate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    idHash: BytesLike,
    contentHash: BytesLike,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    idHash: string,
    contentHash: string,
    issuedAt: bigint
  ];
  export interface OutputObject {
    idHash: string;
    contentHash: string;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialReinstatedEvent {
  export type InputTuple = [idHash: BytesLike];
  export type OutputTuple = [idHash: string];
  export interface OutputObject {
    idHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [idHash: BytesLike, revokedAt: BigNumberish];
  export type OutputTuple = [idHash: string, revokedAt: bigint];
  export interface OutputObject {
    idHash: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerSetEvent {
  export type InputTuple = [issuer: AddressLike, allowed: boolean];
  export type OutputTuple = [issuer: string, allowed: boolean];
  export interface OutputObject {
    issuer: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ImariCredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ImariCredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: ImariCredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  get: TypedContractMethod<
    [idHash: BytesLike],
    [ImariCredentialRegistry.RecordStructOutput],
    "view"
  >;

  issue: TypedContractMethod<
    [idHash: BytesLike, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  issuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  reinstate: TypedContractMethod<[idHash: BytesLike], [void], "nonpayable">;

  revoke: TypedContractMethod<[idHash: BytesLike], [void], "nonpayable">;

  setIssuer: TypedContractMethod<
    [issuer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[isPaused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [next: AddressLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [idHash: BytesLike, presentedHash: BytesLike],
    [[bigint, boolean] & { status: bigint; matches: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<
    [idHash: BytesLike],
    [ImariCredentialRegistry.RecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issue"
  ): TypedContractMethod<
    [idHash: BytesLike, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reinstate"
  ): TypedContractMethod<[idHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[idHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIssuer"
  ): TypedContractMethod<
    [issuer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[isPaused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[next: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [idHash: BytesLike, presentedHash: BytesLike],
    [[bigint, boolean] & { status: bigint; matches: boolean }],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialReinstated"
  ): TypedContractEvent<
    CredentialReinstatedEvent.InputTuple,
    CredentialReinstatedEvent.OutputTuple,
    CredentialReinstatedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerSet"
  ): TypedContractEvent<
    IssuerSetEvent.InputTuple,
    IssuerSetEvent.OutputTuple,
    IssuerSetEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,bytes32,uint64)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialReinstated(bytes32)": TypedContractEvent<
      CredentialReinstatedEvent.InputTuple,
      CredentialReinstatedEvent.OutputTuple,
      CredentialReinstatedEvent.OutputObject
    >;
    CredentialReinstated: TypedContractEvent<
      CredentialReinstatedEvent.InputTuple,
      CredentialReinstatedEvent.OutputTuple,
      CredentialReinstatedEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,uint64)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerSet(address,bool)": TypedContractEvent<
      IssuerSetEvent.InputTuple,
      IssuerSetEvent.OutputTuple,
      IssuerSetEvent.OutputObject
    >;
    IssuerSet: TypedContractEvent<
      IssuerSetEvent.InputTuple,
      IssuerSetEvent.OutputTuple,
      IssuerSetEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
  };
}
