/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImariCredentialRegistry } from "./ImariCredentialRegistry";
export * as factories from "./factories";
export { ImariCredentialRegistry__factory } from "./factories/ImariCredentialRegistry__factory";
